corewar/corewar-ui

package-lock.json
package.json
src/containers/simulator/cell.js
src/containers/simulator/core.js
src/containers/simulator/index.js
src/modules/parser.js
src/modules/simulator.js

Output the initial core to screen

Amend output core to screen and create placeholders in state

---

package-lock.json
package.json
src/containers/app/App.css
src/containers/parser/index.js
src/containers/simulator/cell.css
src/containers/simulator/cell.js
src/containers/simulator/core.js
src/containers/simulator/index.js
src/containers/simulator/simulator.css
src/modules/parser.js
src/modules/simulator.js

This allows multiple warriors to be shown:

Allow multiple warriors

---

package-lock.json
package.json
src/containers/app/App.css
src/containers/parser/index.js
src/containers/simulator/cell.css
src/containers/simulator/cell.js
src/containers/simulator/core.js
src/containers/simulator/index.js
src/containers/simulator/simulator.css
src/modules/parser.js
src/modules/simulator.js
src/tests/parser/parser.test.js
src/tests/simulator/cell.test.js
src/tests/simulator/core.test.js
src/tests/simulator/simulator.test.js

Add some really basic smoke tests for the main components in the app so far

Add more ui teats

---

src/containers/simulator/index.js
src/modules/simulator.js

Fixes #36 and builds on #37 by removing some extra bits

Bug 36 cannot step

---

package-lock.json
package.json
src/containers/app/debugInterface.css
src/containers/app/debugInterface.js
src/containers/parser/parserOutput.js
src/containers/parser/warriorList.css
src/containers/parser/warriorList.js
src/containers/simulator/canvasCore.js
src/containers/simulator/simulatorContainer.css
src/containers/simulator/simulatorControls.css
src/containers/simulator/simulatorStatus.css
src/containers/simulator/simulatorStatus.js
src/index.js
src/modules/simulator.js

Add's a status bar to the simulator to show whether it's running, how many warriors are loaded etc.

Add basic simulator status bar

---

package-lock.json
package.json
src/containers/app/debugInterface.css
src/containers/app/debugInterface.js
src/containers/parser/messagePanel.css
src/containers/parser/messagePanel.js
src/containers/parser/parseContainer.css
src/containers/parser/parseIcon.css
src/containers/parser/parseIcon.js
src/containers/parser/parserOutput.js
src/containers/parser/warriorList.css
src/containers/parser/warriorList.js
src/containers/simulator/canvasCore.js
src/containers/simulator/simulatorContainer.css
src/containers/simulator/simulatorControls.css
src/containers/simulator/simulatorStatus.css
src/containers/simulator/simulatorStatus.js
src/index.js
src/modules/simulator.js

adds an icon to indicate whether or not parsing was successful

Add parse icon

---

package-lock.json
package.json
src/containers/app/debugInterface.css
src/containers/app/debugInterface.js
src/containers/parser/inputSectionHeader.js
src/containers/parser/messagePanel.css
src/containers/parser/messagePanel.js
src/containers/parser/outputSectionHeader.js
src/containers/parser/parseContainer.css
src/containers/parser/parseContainer.js
src/containers/parser/parseIcon.css
src/containers/parser/parseIcon.js
src/containers/parser/parserInput.css
src/containers/parser/parserOutput.css
src/containers/parser/parserOutput.js
src/containers/parser/sectionHeader.css
src/containers/parser/warriorList.css
src/containers/parser/warriorList.js
src/containers/simulator/canvasCore.js
src/containers/simulator/simulatorContainer.css
src/containers/simulator/simulatorControls.css
src/containers/simulator/simulatorStatus.css
src/containers/simulator/simulatorStatus.js
src/index.js
src/modules/simulator.js

Add's section headers for the parser so it's more explicit what the different areas are:

Add section headers

---

package-lock.json
package.json
src/containers/parser/inputSectionHeader.js
src/containers/parser/outputSectionHeader.js
src/containers/parser/warriorList.js
src/tests/app/app.test.js
src/tests/app/login.test.js
src/tests/app/logo.test.js
src/tests/app/siteHeader.test.js
src/tests/parser/inputSectionHeader.test.js
src/tests/parser/messagePanel.test.js
src/tests/parser/outputSectionHeader.test.js
src/tests/parser/parseIcon.test.js
src/tests/parser/parserInput.test.js
src/tests/parser/parserOutput.test.js
src/tests/parser/warriorList.test.js
src/tests/simulator/playPauseControl.test.js

Add a series of UI tests for the parser side of things.
Simulator tests still in progress

Add ui smoke tests

---

package-lock.json
src/containers/app/debugInterface.css
src/containers/app/debugInterface.js
src/containers/simulator/canvasCore.js
src/containers/simulator/coreLocation.css
src/containers/simulator/coreLocation.js
src/containers/simulator/coreVisualiser.css
src/containers/simulator/coreVisualiser.js
src/containers/simulator/simulatorContainer.css
src/containers/simulator/simulatorContainer.js
src/containers/simulator/simulatorStatus.css
src/containers/simulator/simulatorStatus.js
src/modules/simulator.js

Added a section to the core which shows the state of the core +/-5 when you click on a cell.
Coloured the cell you clicked on blue so it's clear in the row which is the current selector.
TODO: These is nothing on the canvas to show where you have selected

Add core visualation bar

---

wercker.yml

add env output

---

src/containers/parser/controlButton.js
src/containers/simulator/playPauseControl.js
src/containers/simulator/resetControl.js
src/containers/simulator/simulatorStatus.js
src/containers/simulator/stepControl.js
src/modules/parser.js

Allow the button on clicks to respond to the same area as the css `:hover` class.
Fixes #92
Also includes rogue missing re-init function #54

Fix button clickable areas

---

src/containers/simulator/coreVisualiser.js
src/containers/simulator/fastForwardControl.js
src/containers/simulator/playPauseControl.js
src/containers/simulator/rewindControl.js
src/containers/simulator/simulatorContainer.js
src/containers/simulator/simulatorControls.js
src/modules/parser.js
src/modules/simulator.js

Add in basic ff/rw functionality. 
Need to decide some max / mins and a suitable step maybe?
Resolves #82

Implement ff rw buttons

---

src/containers/simulator/canvasCore.js
src/containers/simulator/coreContainer.css
src/containers/simulator/coreContainer.js
src/containers/simulator/coreLocation.css
src/containers/simulator/playPauseControl.js
src/containers/simulator/simulatorContainer.css
src/containers/simulator/simulatorContainer.js

Increase width and prevent non initalised cores from crashing

---

src/containers/parser/parserOutput.css
src/containers/simulator/canvasCore.js
src/containers/simulator/coreContainer.css
src/containers/simulator/coreContainer.js
src/containers/simulator/coreLocation.css
src/containers/simulator/playPauseControl.js
src/containers/simulator/simulatorContainer.css
src/containers/simulator/simulatorContainer.js

Fix 98 word wrap

---

package-lock.json
package.json
src/containers/simulator/canvasCore.js
src/containers/simulator/finishRoundControl.js
src/containers/simulator/simulatorContainer.js
src/containers/simulator/simulatorControls.js
src/modules/simulator.js

Add the finish round control and ties it to `finishRound` in the actions.
Calls run and responds by concatting the messages instead of pushing one by one.
Works perfectly :shipit: 
Resolves #31

Most naive / simple finishRound impl

---

package-lock.json
package.json
src/containers/simulator/canvasCore.js
src/containers/simulator/finishRoundControl.js
src/containers/simulator/simulatorContainer.js
src/containers/simulator/simulatorControls.js
src/modules/simulator.js

Resolve #106 by copy pasting huge chunks of code.
TODO: Refactor all this, but want to finalise the remaining processes needed to finish off the core functionality before doing so

Run and finish need to re init

---

src/containers/simulator/coreLocation.css
src/containers/simulator/coreLocation.js
src/containers/simulator/coreVisualiser.js
src/containers/simulator/simulatorContainer.js
src/containers/simulator/simulatorControls.css
src/modules/simulator.js

Colour the core visualiser in the colour of the warrior which last executed the instruction.
TODO: I'm not exactly sure these are showing the right info / colour...to discuss

Colour core visualiser

---

src/modules/simulator.js

Re-call getCoreInstructions when you call step 
Resolves #90

Rerun getCoreInstructions on step

---

package-lock.json
package.json
src/containers/simulator/simulatorStatus.css
src/containers/simulator/simulatorStatus.js
src/modules/simulator.js
src/tests/simulator/simulatorStatus.test.js

The winner is now reported by colour and metadata and winners with id's of 0 no longer cause problems
#112 
This would be great to demo if only my seemingly working fix for the earlier problem actually worked :(

Add a better display winners with colour and metadata

---

package-lock.json
package.json
src/components/simulator/canvasCore.js
src/components/simulator/coreInput.css
src/components/simulator/coreInput.js
src/components/simulator/runProgressIndicator.js
src/helpers/arrayHelpers.js
src/sagas/parserSagas.js
src/sagas/simulatorSagas.js
src/tests/helpers/arrayHelpers.test.js
src/tests/sagas/parserSaga.test.js
src/tests/sagas/simulatorSaga.test.js

Init now stops any running round.
Also resolves an issue where messages which are in the canvas state when calling init continue to be processed after the core init / reset was dispatched

Init should stop any active round

---

src/components/app/errorBoundary.js
src/components/simulator/canvasCore.js
src/containers/parser/parseControls.js
src/tests/actions/creator.test.js
src/tests/actions/parserActions.test.js
src/tests/actions/simulatorActions.test.js
src/tests/app/errorBoundary.test.js
src/tests/app/siteHeader.test.js
src/tests/parser/parseControls.test.js
src/tests/reducers/simulatorReducer.test.js
src/tests/simulator/settingsControl.test.js
src/tests/simulator/speedControl.test.js

highlight the address of each 'CORE_ACCESS' as it's rendered in white.
Also, death to the semi!

add a 'renderCurrentTask' function

---

src/components/simulator/canvasCore.js
src/sagas/simulatorSagas.js

Update the clear rect issue.
Perf is ok up to 500x, 2000 a bit laggy

Fix white edge bug

---

package-lock.json
package.json
src/components/simulator/coreInput.js

fix task rendering

---

src/components/app/inputInterface.js
src/components/app/login.js
src/components/app/outputInterface.js
src/components/app/parserInterface.js
src/components/styledComponents/compiledOutput.js
src/components/styledComponents/mobile/controls.js
src/components/styledComponents/tablet/controls.js
src/components/styledComponents/tablet/main.js
src/containers/app/index.js
src/containers/app/mobileLayout.js
src/containers/app/tabletLayout.js
src/styles/sourceCode.js

Add sidewang for tablet layouts

Ui version 2

---

package-lock.json
package.json
src/actions/simulatorActions.js
src/components/simulator/canvasCore.js
src/components/simulator/coreInterface.js
src/containers/simulator/coreContainer.js
src/reducers/simulatorReducers.js
src/sagas/simulatorSagas.js

I promise I'll move onto proper branches and PR's soon....soon!

Implement republish in a rough and ready way

---

src/features/simulator/core.js

This is the sprite rendering implementation we discussed.
It removes most of the previous rendering mechanisms and replaces them with a sprite based alternative.
The highlight on the current execution address wasn't compatible with the new sprite based approach and it wasn't implemented correctly anyway so I have removed it and raised #179 to deal with this.
BTW rendering is looking hot!

Sprite rendering

---

src/features/common/headerControls.js
src/features/simulator/simulatorLayout.js

Fixes the simulator background #188

Fix simulator background

---

src/features/simulator/core.js
src/helpers/throttle.js

Throttle the resize event to 200ms #182

Throttle resize

---

src/features/simulator/speedControl.js

Fix the odd border non-overlap issue and remove other borders

Fix speed control borders

---

src/features/fileManager/fileManager.js
src/features/simulator/core.js

Highlights the current cell and clears the canvas beforehand.
Has fuzzy edges still but removes the crash #185

add rough click to highlight functionality

---

src/features/simulator/sagas.js
src/features/simulator/warriors.js

Such as clearing when reset / added #186

Change the way tasks are handled to ensure consistent reporting

---

src/features/onboarding/home.js

Increase the factor of awesomeness

Update landing page

---

src/features/common/siteNav.js
src/features/onboarding/home.js
src/features/signup/reducer.js
src/features/signup/signupContainer.js
src/features/simulator/reducer.js
src/features/tutorial/actions.js
src/features/tutorial/reducer.js
src/features/tutorial/tutorialContainer.js
src/index.js
src/reducers/index.js

First stab at writing a tutorial for the Imp #163

Add tutorial for writing an Imp

---

src/features/parser/reducer.js

Does what it says on the tin. Fixes #190

Auto dismiss file manager

---

src/features/app/appContainer.js
src/features/parser/actions.js
src/features/parser/combinedContainer.js
src/features/parser/console.js
src/features/parser/controlsContainer.js
src/features/parser/inputContainer.js
src/features/parser/reducer.js
src/features/parser/sagas.js

Renames 'messages' to 'console' where appropriate and makes the console toggleable
Fixes #191

Console should toggle

---

src/features/signup/sagas.js

Correct error message text

---

package-lock.json
package.json
src/features/common/theme.js
src/features/documentation/concepts.js
src/features/documentation/documentation.js
src/features/documentation/documentationContent.js
src/features/documentation/impTutorialContainer.js
src/index.js

Fixes #163 
Fixes #215 
Will likely need to be refined post review of content

Add intro to corewar

---

src/features/simulator/core.js

Clear the core ara each time the grid is rendered

---

package-lock.json
package.json
src/features/common/theme.js
src/features/notifications/notificationContainer.js

Spent ages trying to figure out how to animate styled components, finally got it working but seeing some odd things with the order things are removed.
Will suffice for the time being
Fixes #197

animate toasts and colour better

---

src/features/common/identicon.js
src/features/documentation/documentationContent.js
src/features/parser/sagas.js
src/features/simulator/simulatorLayout.js

use white as a default colour for warrior which aren't specifically coloured

---

src/features/common/warriorPanel.js

prevent too many warriors breaking out of container

---

src/features/simulator/instructions.js

add simple intro text for instruction area

---

src/features/simulator/instruction.js
src/features/simulator/roundProgress.js

colour instructions based on warrior index

---

src/features/simulator/instruction.js
src/features/simulator/instructions.js

add border to focussed address

---

package-lock.json
package.json
src/features/simulator/core.js

Addresses #179 
Handles NEXT_EXECUTION messages from core library and highlighted the  corresponding address using solid white.
Next execution is not correctly highlighted after initialise, a message needs to be raised by the core in this situation - have raised an issue in core library: https://github.com/gareththegeek/corewar/issues/175

Render solid, white cell for next execution address

---

src/features/parser/sagas.js
src/features/simulator/roundProgress.js

catch init attempts in parse with no valid warriors

---

src/features/notifications/actions.js
src/features/notifications/notificationContainer.js
src/features/notifications/reducer.js
src/features/notifications/sagas.js
src/helpers/arrayHelpers.js
src/helpers/guid.js

Fixes #254 
Solution ended up being a bit more complex then first planned.

254 fix toast add remove

---

src/cssreset.css
src/features/app/mobileLayout.js
src/features/common/fontAwesomeButton.js
src/features/common/rootGrid.js
src/features/simulator/core.js
src/index.js

240 amend button state

---

src/index.js

fix overflow-x to ensure ffox displays correctly

---

package.json
src/features/simulator/core.js

Resolves #270 
Render next execution highlight to interactive canvas layer
Store the selected core address for core inspection in local state and re-render every frame

Highlight fix

---

src/features/parser/combinedContainer.js
src/features/parser/sourceCodeTextArea.js

Resolves #284 by removing requirement that warrior has source before entering into the parse saga

Fix source code entry

---

package-lock.json
package.json

Bump packages to remove security vulnerabilities

Bump packages for security vulnerabilities

---

src/features/documentation/initialState.js
src/features/documentation/reducer.js
src/features/feedback/initialState.js
src/features/feedback/reducer.js
src/features/notifications/initialState.js
src/features/notifications/reducer.js
src/features/parser/initialState.js
src/features/parser/reducer.js
src/features/signup/initialState.js
src/features/signup/reducer.js
src/features/simulator/initialState.js
src/features/simulator/reducer.js
src/tests/reducers/parserReducer.test.js
src/tests/reducers/simulatorReducer.test.js

Extract initial state into separate files, resolves #297

Add initial state

---

src/features/documentation/initialState.js
src/features/documentation/reducer.js
src/features/feedback/initialState.js
src/features/feedback/reducer.js
src/features/notifications/initialState.js
src/features/notifications/reducer.js
src/features/parser/initialState.js
src/features/parser/reducer.js
src/features/signup/initialState.js
src/features/signup/reducer.js
src/features/simulator/initialState.js
src/features/simulator/reducer.js
src/features/simulator/sagas.js
src/tests/reducers/parserReducer.test.js
src/tests/reducers/simulatorReducer.test.js

Fixes #300 - had changed a method call mistakenly and not realised

300 error with core init

---

src/features/parser/sagas.js

Protect the colour methods from `undefined`'s and provide a default colour

---

.prettierrc.json
src/features/app/app.js
src/features/app/tabletLayout.js
src/features/common/controls.js
src/features/common/mobilePage.js
src/features/common/tabLink.js
src/features/common/warriorPanel.js
src/features/navbar/navbar.js
src/features/parser/compiledOutput.js
src/features/parser/outputContainer.js
src/features/simulator/controlsContainer.js
src/features/topbar/logo.js
src/features/topbar/siteHeader.js
src/features/warriorManager/warriorManagerContainer.js

Rejig the navbar and sidebar to accomodate new styles and make way for the upcoming two mode operation 'playa mode!'

Adjust nav and sidebar

---

README.md

Give the readme on Github a snazzy netflify badge

Update build status to use netlify badge
